# This is a basic workflow to help you get started with Actions

name: Build and push executable artifact

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job_1:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: pymodoro-gui

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: pymodoro-exe
          path: pymodoro-gui/dist/windows
          retention-days: 1

  job_2:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: executable    
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        name: pymodoro-exe
        path: Executable/    
        
    - name: Add, commit and push
      run: |    
          git add Executable/
          git commit -m "New executable"
          git push
